// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwk5ANKaBVWnAE56ZzeneWaDCQ5fhHcM',
    appId: '1:553421177600:web:8ebf114478caf3635ba9e5',
    messagingSenderId: '553421177600',
    projectId: 'homify-55715',
    authDomain: 'homify-55715.firebaseapp.com',
    storageBucket: 'homify-55715.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPd6TYeSqtj1njSnse-msX7OtBM7OaoVw',
    appId: '1:553421177600:android:678946ddff6074a35ba9e5',
    messagingSenderId: '553421177600',
    projectId: 'homify-55715',
    storageBucket: 'homify-55715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRhlzXlIoU1R0CdyK0FyA6y-uSCB7nk4o',
    appId: '1:553421177600:ios:582dbec642f9f6be5ba9e5',
    messagingSenderId: '553421177600',
    projectId: 'homify-55715',
    storageBucket: 'homify-55715.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRhlzXlIoU1R0CdyK0FyA6y-uSCB7nk4o',
    appId: '1:553421177600:ios:582dbec642f9f6be5ba9e5',
    messagingSenderId: '553421177600',
    projectId: 'homify-55715',
    storageBucket: 'homify-55715.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwk5ANKaBVWnAE56ZzeneWaDCQ5fhHcM',
    appId: '1:553421177600:web:78850121fad96a095ba9e5',
    messagingSenderId: '553421177600',
    projectId: 'homify-55715',
    authDomain: 'homify-55715.firebaseapp.com',
    storageBucket: 'homify-55715.firebasestorage.app',
  );
}
